version: '3.5'

services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - JWT_KEY=SUPERSECRETJWTKEY
    ports:
      - 3000:3000
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
